site_name: ""
site_url: https://careamics.github.io/
repo_url: https://github.com/CAREamics/careamics
repo_name: CAREamics
#edit_uri: https://github.com/CAREamics/careamics.github.io/blob/main/docs/
edit_uri: "" # disable the edit button

nav:
  - Home: index.md
  - Installation: installation.md
  - Current State: current_state.md
  - Guides:
      - Guides: guides/index.md
      - Configuration:
          - guides/configuration/index.md
          - guides/configuration/convenience_functions.md
          - guides/configuration/save_load.md
          - guides/configuration/build_configuration.md
          - guides/configuration/full_spec.md
          - guides/configuration/algorithm_requirements.md
          - guides/configuration/advanced_configuration.md
          - guides/configuration/understanding_errors.md
      - Using CAREamics:
          - guides/usage/index.md
          - guides/usage/careamist.md
          - guides/usage/training.md
          - guides/usage/datasets.md
          - guides/usage/prediction.md
          - guides/usage/model_export.md
      - Lightning API:
          - guides/lightning_api/index.md
      - Developer resources:
          - Developer resources: guides/dev_resources/index.md
          - guides/dev_resources/contribute.md
          - guides/dev_resources/website.md
          - guides/dev_resources/docstring.md
      - Command-line interface:
          - guides/cli/index.md
  - Applications: applications/
  - Algorithms:
      - algorithms/index.md
      - Noise2Void: algorithms/n2v/

  - Code Reference: reference/

theme:
  name: material
  logo: assets/banner_careamics_large.png
  favicon: assets/icon_careamics.png
  custom_dir: docs/overrides
  font: false
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

  features:
    #- navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    # - navigation.footer  # next/previous links in footer
    - navigation.content_next # next/previous links bottom of content
    # - navigation.instant # hard to use with javascript on page load
    # - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - navigation.icons

markdown_extensions:
  #- pymdownx.extra # markdown in html (includes commented extensions below)
  - attr_list
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs/overrides/.icons/octicons # to use emojis in the cards
        - temp/ # for the code snippets in the guides
  # - pymdownx.progressbar:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"

plugins:
  - search
  - tags

  # jupyter notebooks: https://pypi.org/project/mkdocs-jupyter/
  - mkdocs-jupyter:
      no_input: False
      remove_tag_config:
        # https://nbconvert.readthedocs.io/en/latest/removing_cells.html
        remove_all_outputs_tags:
          - remove_output
        remove_input_tags:
          - hide_code

  # Generate code documentation from other modules
  # generate .md for a python modules
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
        - scripts/gen_jupyter_nav.py

  # allow navigation from a file, used together with gen-files
  - literate-nav:
      nav_file: SUMMARY.md

  # generate docstrings
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy

  # minify files
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        # - stylesheets/extra.css
        # - stylesheets/termynal.css
      js_files:
        # - javascripts/extra.js
        # - javascripts/termynal.js

  # check spelling in all files, including code documentation
  - spellcheck:
      backends: # the backends you want to use
        - codespell: # or nested configs
            dictionaries: [clear, rare]

watch:
  - docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CAREamics/careamics
  version:
    provider: mike

extra_javascript:
  - javascripts/termynal.js
  - javascripts/extra.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/grid_menu.css
  - stylesheets/termynal.css
  - https://unpkg.com/katex@0/dist/katex.min.css
