site_name: My Docs

nav:
  - Home: index.md
  - Guide:
      - guide/index.md
  - Code Reference: reference/

theme:
  name: material
  font: false
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    # - navigation.footer  # next/previous links in footer
    - navigation.content_next # next/previous links bottom of content
    # - navigation.instant  # hard to use with javascript on page load
    # - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - navigation.icons

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

plugins:
  # potentially we could use this: https://github.com/jdoiro3/mkdocs-multirepo-plugin
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - spellcheck:
      backends: # the backends you want to use
        - codespell: # or nested configs
            dictionaries: [clear, rare]

watch:
  - docs
